### ISSUE TITLE
Create TSMC 65nm synthesis script

### ISSUE THREAD

**Issue by dale40** [scalable-arch/rtl-actions#1]

**Comment by gju06051** [comment]
![image](https://github.com/scalable-arch/rtl-actions/assets/37738888/87c751fc-409c-4989-a40b-184be6734bef)

실제 환경 test해보기 위해서 AIDC와 rtl-actions repo를 fork하였고 exa서버에서 self-hosted runner default로 추가하여 수행하였습니다. 원하시는 방향이 맞으시면 목요일 오전 서브시스템 미팅 이후에 피드백 반영하여 AIDC및 rtl-actions repo에 수정하여 반영하겠습니다. 

해당 TSMC 65nm 합성 과정을 위해서 setting은 다음과 같이 구성하였습니다. 

AIDC repo
1) AIDC repo의 .workflows에 syn_TSMC65.yml workflow 작성
![image](https://github.com/scalable-arch/rtl-actions/assets/37738888/6c0a55a5-081e-417f-95f6-8dad0bffdcc8)

2) AIDC repo에 env.source 환경변수 세팅하는 shell 작성
![image](https://github.com/scalable-arch/rtl-actions/assets/37738888/46b9edb1-2055-4062-8f35-01598b346bd8)

rtl-actions submodule repo
1) syn_TSMC65 directory에 action.yml 작성
![image](https://github.com/scalable-arch/rtl-actions/assets/37738888/fbdc922c-45f1-4d6e-956b-00ce485efe99)

2) bin directory에 action.syn_TSMC65 가져오기
![image](https://github.com/scalable-arch/rtl-actions/assets/37738888/6f4163b8-8161-493b-b347-abc0f71ffa58)

3) tcl directory 생성 및 syn_TSMC65.tcl 가져오기

따라서 아래와 같이 rtl-actions directory를 구성하였고 강조된 부분이 해당 syn_TSMC65 workflow에 사용되는 rtl-actions 파일들입니다. 
![image](https://github.com/scalable-arch/rtl-actions/assets/37738888/8333822b-b1ae-45cb-953a-0a31616a7644)

동작 과정 
1) HW_REPO(e.g., AIDC repo) ./github/.workflow가 event(e.g., branch pull request to main, workflow_dispatch, schedule) 발생 시 syn_TSMC65.yml workflow queue
2) EXA서버의 self-hosted runner polling으로 syn_TSMC65.yml job을 가져옴
3) actions/checkout@v3 동작으로 pull request code를 self-hosted runner로 가져옴
4) Synthesis에서 rtl-actions/syn_TSMC65/action.yml 동작
5) syn_TSMC65/action.yml에 정의된 AIDC/env.source 실행으로 환경변수 설정
6) syn_TSMC65/action.yml에 정의된 rtl-actions/bin/action.syn_TSMC65를 통해서 tcl을 dc_shell로 넘겨주고 tcl에 정의된 VCS 동작 수행
7) syn_TSMC65/action.yml에 정의된 syn-report/action.yml 수행으로 VCS에 의해 생성된 report를 github actions console에 cat으로 출력
8) workflow 마무리 동작 수행
